### ISSUE TITLE
Strange entires showing in z-nomp

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [poolgold/z-nomp-bitcoin-gold#20]
It it normal to be seeing entries like this? I have just started seeing these when z-nomp starts and a miner joins

Share processor Redis execution time: 1 Executed operations: 44
Execution time: 1 PileUp: 0 Executed operations: 14
Share processor Redis execution time: 1 Executed operations: 9
Execution time: 0 PileUp: 0 Executed operations: 3
Share processor Redis execution time: 1 Executed operations: 24
Execution time: 1 PileUp: 0 Executed operations: 8
Execution time: 0 PileUp: 0 Executed operations: 8
Share processor Redis execution time: 1 Executed operations: 24
Share processor Redis execution time: 1 Executed operations: 21
Execution time: 1 PileUp: 0 Executed operations: 7
Execution time: 1 PileUp: 0 Executed operations: 7
Share processor Redis execution time: 3 Executed operations: 21
Share processor Redis execution time: 0 Executed operations: 18
Execution time: 1 PileUp: 0 Executed operations: 6
Share processor Redis execution time: 2 Executed operations: 27
Execution time: 1 PileUp: 0 Executed operations: 9
Share processor Redis execution time: 1 Executed operations: 33
Execution time: 0 PileUp: 0 Executed operations: 11
Share processor Redis execution time: 1 Executed operations: 21
Execution time: 1 PileUp: 0 Executed operations: 7
Execution time: 1 PileUp: 0 Executed operations: 10
Share processor Redis execution time: 3 Executed operations: 30
Share processor Redis execution time: 1 Executed operations: 24
Execution time: 0 PileUp: 0 Executed operations: 8

**Comment by martin-key** [comment]
They will be removed. This is currently dev version.

**Comment by jamiejacksoncumbria** [comment]
ok so all is ok then.
I cant seem to get block notify to work. i have an entry in my .bitcoingold/bitcoingold.conf  but does not notify is that where the entry should be for this version of z-nomp? Path is correct to the script as if i drop it into the command line it say pool updated but is not?

Thanks

**Comment by martin-key** [comment]
Is the daemon on a separate machine ?

**Comment by jamiejacksoncumbria** [comment]
No same machine.

**Comment by jamiejacksoncumbria** [comment]
Also getting this message IN RED

2018-01-04 01:26:41 [Pool]  [bitcoin gold] (Thread 4) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocksubsidy","params":[],"id":1515022001919}
Reponse Data: Work queue depth exceeded
2018-01-04 01:26:41 [Pool]  [bitcoin gold] (Thread 2) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"],"rules":["segwit"]}],"id":1515022001955}
Reponse Data: Work queue depth exceeded
2018-01-04 01:26:41 [Pool]  [bitcoin gold] (Thread 1) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocksubsidy","params":[],"id":1515022001961}

**Comment by jamiejacksoncumbria** [comment]
Sorted was using coin name other than what was in coin.json for block notify. I.e btg bitcoingold not Bitcoin Gold.

**Comment by Gadflyii** [comment]
Is there a way to disable these messages?

**Comment by barrystyle** [comment]
there sure is.. just comment out line 104 of 'libs/shareProcessor.js', and line 305 of 'init.js'
