### ISSUE TITLE
Payment queue issue

### ISSUE THREAD

**Issue by hardx4** [poolgold/z-nomp-bitcoin-gold#6]
Every time z-nomp makes a payment, the next payment in the queue remains in this error for a long period of time, I'd like to know how to resolve this error. The system worked well, payments are being sent, but only after a long period of time. And this always happens after a payment. Error on red color.

![capturar 4](https://user-images.githubusercontent.com/7688208/32751579-d271a310-c89c-11e7-98fd-58e92477dadf.PNG)

**Comment by gateway** [comment]
I have a question about that.. 

Payment goes into "address" filed in the config.. does it get transfered to "tadaddress" field?

If so, that would mean once you have the 100 confirmations, then it sends it to another address and you have to wait for another 100 confirmations then it tries sendmany with ""

Could this be a part of the issue if not what is taddress used for?

**Comment by hardx4** [comment]
@gateway  Payments are successfully sent, but when a set of 3 blocks is paid, the remainder already confirmed remains in that error for a long period of time, until at some point the payment occurs.
We've already made several payments, but the payments were slow because of that. This stays like this for hours.

**Comment by gateway** [comment]
right, i was just wanting a bit more clarification on the system as well.  I think the 100 confirmations may be messing things up on timing?

**Comment by martin-key** [comment]
@gateway 100 confirmation are required by the network. I agree that it is a lot of time.

**Comment by martin-key** [comment]
The problem is caused by incorrect rounding. I think it is fixed as poolgold has no such issue.
